services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: cooperfilmes
      POSTGRES_PASSWORD: eureka
      POSTGRES_DB: cooperfilmes
      PGDATA: /data/postgres
    volumes:
      - ./postgres/:/data/postgres
      - ../database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  cooperfilmes-be:
    container_name: backend-cooperfilmes
    image: cooperfilmes
    ports:
      - "8091:8091"
    restart: unless-stopped
    depends_on:
      - postgres