services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: cooperfilmes
      POSTGRES_PASSWORD: eureka
      PGDATA: /data/postgres
    volumes:
      - ./postgres/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped